package com.dma.web;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

public class Test3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		String query = "SELECT tableid AS Table_Name, columnid AS Column_Name, columnlabel AS Column_Label FROM syscolumn where tableid = ? and columnid IN (?)";
		
		List<String> tables = new ArrayList<String>();
		tables.add("S_SAMPLE");
		tables.add("S_BATCH");
		
		String columns = "('S_SAMPLEID','SAMPLEDESC','SAMPLETYPEID','CREATEDT','CREATEBY','CREATETOOL','MODDT','MODBY','SUBMITTERID','MODTOOL','SUBMITTEDDT','AUDITDEFERFLAG','NOTES','AUDITSEQUENCE','TRACELOGID','USERSEQUENCE','REVIEWREQUIREDFLAG','PRIORITY','DISPOSALSTATUS','SAMPLESTATUS','COLLECTIONDT','RECEIVEDDT','PHYSICALCONDITION','BATCHID','PRODUCTID','PROJECTID','SAMPLEPOINTID','LOCATIONID','REQUESTID','STARTTESTINGDT','COMPLETEDT','DISPOSALDT','DUEDT','BASEDONSAMPLEID','COLLECTEDBY','TEMPLATEFLAG','RECEIVEDBY','DISPOSEDBY','REVIEWEDBY','REVIEWEDDT','REVIEWDISPOSITION','REVIEWREMARKS','NUMBERLABELS','CONTROLSUBSTANCEFLAG','RECEIVEREQUIREDFLAG','COCREQUIREDFLAG','EVENTDT','AUTORECEIVEFLAG','AUTOFINALRPTFLAG','EVENTPLAN','STUDYID','CONDITIONLABEL','EVENTPLANITEM','SCHEDULERULELABEL','SAMPLEFAMILYID','CONFIRMEDBY','CONFIRMEDDT','SSTUDYID','POOLEDFLAG','GLPFLAG','COCFLAG','RESTRICTIONSFLAG','CONCENTRATION','CONCENTRATIONUNITS','STORAGESTATUS','PREVIOUSSTORAGESTATUS','DEVIATIONS','TREATMENTS','ALLOCATEDFORADDRESSID','ALLOCATEDFORADDRESSTYPE','ALLOCATEDFORDEPARTMENTID','PREPTYPEID','STORAGEDISPOSALSTATUS','REAGENTLOTID','QCSAMPLETYPE','U_BATCH_INFO','U_SOURCE','U_SAMPLING_STOR_COND','U_SAMPLECOLLECTER','U_SAMPLING_CONDITION','U_PRODUCT_INFO','U_PDS_NUMBER','U_SUPPLIER','U_COUNTRY','U_PRODUCT_EXPIREDDT','U_EUROPE','U_PRODUCTION_DT','U_PACKAGING_TYPE','U_AMOUNT','U_SIZE_UNITS','U_SUPPLY_DT','U_SAMPLING_NOTES','U_REMARKS_COA','U_INTERNAL_REMARKS','U_SAMPLE_PREP_REMARKS','U_PLANNED_BY','U_INITIAL_BY','U_COMPLETED_BY','U_INPROGRESS_BY','U_CLOSED_BY','U_CANCELLED_BY','U_PREPARATION_STATUS','U_START_TESTING_BY','U_ONHOLD_BY','U_PLANNED_DATE','U_CLOSED_DATE','U_INPROGRESS_DATE','U_ONHOLD_DATE','U_INITIAL_DATE','U_CANCELLED_DATE','U_LABORATORY','U_PREP_REQUIRED_FLAG','SECURITYUSER','SECURITYDEPARTMENT','U_ORIGINE','U_SAMPLING_DT','U_SAMPLING_PACK','U_START_TESTING_DT','U_ONHOLD_REMARKS','U_REVIEW_REMARKS','U_DPT_LOCATION','U_SAMPLEQUANTITY','U_EXPIRATIONDT','U_SAMPLE_LOCATION','U_RECIPE_CODE','U_STATUSPREVIEWHOLD','U_LOCALTIME','U_NUMBER_CLIENT','U_PRODUCTIONSTAGE','U_FIRST_CARTON','U_EVENTID','U_SAMPLINGTIME','U_CONFORMITY','U_EXCIPIOCASEID','U_EXPECTED_STARTDT','U_ERP_NUMBER','U_STORAGE_LOCATION','U_PROCESS_PHASE','SPECIMENTYPE','DISPOSALTARGETDT','SOURCESPID','SOURCESPVERSIONID','SOURCESPLEVELID','SOURCESPSOURCELABEL','BATCHSTAGEID','ACTIVEFLAG','PRODUCTVERSIONID','INSTRUMENTID','WORKORDERID','CLASSIFICATION','U_REFERENCE1','U_BATCH1','U_SUPPLIER2','U_REFERENCE2','U_BATCH2','U_SUPPLIER3','U_REFERENCE3','U_BATCH3','U_PALLETID','U_STUDYSITEID','U_SUBJECTID','U_VISITID','U_CALI_STATUS','U_PHENOTYPE','U_SHIPMENTDT','U_RETURNDDT','U_EXTLAB_RECEIVEDT','U_PRODUCTION_SITE','U_CALI_VOLUME','U_TOUGHED_TIME','U_MASTERSAMPLEID')";
		
		if(!query.isEmpty() && StringUtils.countMatches(query, " (?)") == 1 && StringUtils.countMatches(query, " = ? ") == 1){
			query = StringUtils.replace(query, " = ?", " = '" + tables.get(0) + "'");
			query = StringUtils.replace(query, " (?)", " " + columns);
			
			
			
			System.out.println(query);
			
		}

	}

}
